-- MySQL Script generated by MySQL Workbench
-- Sun Nov 11 16:56:13 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USUARIOS` (
  `ID_USUARIOS` INT NOT NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_USUARIOS`),
  UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PAISES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PAISES` (
  `ID_PAIS` INT NOT NULL,
  `NOMBRE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_PAIS`),
  UNIQUE INDEX `NOMBRE_UNIQUE` (`NOMBRE` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CIUDADES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CIUDADES` (
  `ID_CIUDAD` INT NOT NULL,
  `NOMBRE` VARCHAR(100) NULL,
  `PAIS_ID_PAIS` INT NOT NULL,
  PRIMARY KEY (`ID_CIUDAD`),
  INDEX `fk_CIUDAD_PAIS_idx` (`PAIS_ID_PAIS` ASC),
  CONSTRAINT `fk_CIUDAD_PAIS`
    FOREIGN KEY (`PAIS_ID_PAIS`)
    REFERENCES `mydb`.`PAISES` (`ID_PAIS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PREFERENCIAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PREFERENCIAS` (
  `ID_PREFERENCIA` INT NOT NULL  AUTO_INCREMENT,
  `GRADO` VARCHAR(45) NOT NULL,
  `USUARIOS_ID_USUARIOS` INT NOT NULL,
  `PAIS_ID_PAIS` INT NOT NULL,
  `CIUDAD_ID_CIUDAD` INT NOT NULL,
  PRIMARY KEY (`ID_PREFERENCIA`, `USUARIOS_ID_USUARIOS`, `PAIS_ID_PAIS`, `CIUDAD_ID_CIUDAD`),
  INDEX `fk_PREFERENCIAS_USUARIOS1_idx` (`USUARIOS_ID_USUARIOS` ASC) ,
  INDEX `fk_PREFERENCIAS_PAIS1_idx` (`PAIS_ID_PAIS` ASC) ,
  INDEX `fk_PREFERENCIAS_CIUDAD1_idx` (`CIUDAD_ID_CIUDAD` ASC) ,
  CONSTRAINT `fk_PREFERENCIAS_USUARIOS1`
    FOREIGN KEY (`USUARIOS_ID_USUARIOS`)
    REFERENCES `mydb`.`USUARIOS` (`ID_USUARIOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PREFERENCIAS_PAIS1`
    FOREIGN KEY (`PAIS_ID_PAIS`)
    REFERENCES `mydb`.`PAISES` (`ID_PAIS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PREFERENCIAS_CIUDAD1`
    FOREIGN KEY (`CIUDAD_ID_CIUDAD`)
    REFERENCES `mydb`.`CIUDADES` (`ID_CIUDAD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
